#!/bin/sh
# Simple bootstrap script for the installer. This script uses the bundled
# Ruby interpreter binary whenever possible, and falls back to the system's
# Ruby interpreter if no suitable bundled Ruby interpreter exists.
dir=`dirname "$0"`
cd "$dir"
platform="`uname`-`uname -m`"
if test -f "runtime/$platform/ruby"; then
	#echo "Using 'runtime/$platform/ruby'"
	exec "runtime/$platform/ruby" installer.rb
else
	exec ruby installer.rb
fi
